### ISSUE TITLE
Installation error Windows 10 

### ISSUE THREAD

**Issue by venterce** [kelyvin/Google-Messages-For-Desktop#20]
Hi,

I'm not able to install the Windows version, I get an error when running the nativefiler Windows install. Here are the results of the two installs:

> > core-js@2.6.9 postinstall C:\Users\vente\AppData\Roaming\npm\node_modules\nativefier\node_modules\babel-polyfill\node_modules\core-js
> > node scripts/postinstall || echo "ignore"
> 
> C:\Users\vente\AppData\Roaming\npm\nativefier -> C:\Users\vente\AppData\Roaming\npm\node_modules\nativefier\lib\cli.js
> nativefier@7.7.0 C:\Users\vente\AppData\Roaming\npm\node_modules\nativefier
> ├── progress@2.0.3
> ├── commander@2.20.0
> ├── ncp@2.0.0
> ├── tmp@0.0.33 (os-tmpdir@1.0.2)
> ├── loglevel@1.6.4
> ├── hasbin@1.2.3 (async@1.5.2)
> ├── sanitize-filename@1.6.3 (truncate-utf8-bytes@1.0.2)
> ├── validator@10.11.0
> ├── axios@0.18.1 (is-buffer@2.0.3, follow-redirects@1.5.10)
> ├── async@2.6.3
> ├── source-map-support@0.5.13 (buffer-from@1.1.1, source-map@0.6.1)
> ├── shelljs@0.8.3 (interpret@1.2.0, glob@7.1.4, rechoir@0.6.2)
> ├── cheerio@1.0.0-rc.3 (entities@1.1.2, dom-serializer@0.1.1, css-select@1.2.0, htmlparser2@3.10.1, parse5@3.0.3)
> ├── gitcloud@0.1.0 (axios@0.9.1, source-map-support@0.4.18, cheerio@0.20.0)
> ├── page-icon@0.3.0 (file-type@3.9.0, axios@0.9.1, source-map-support@0.4.18, cheerio@0.20.0)
> ├── electron-packager@12.2.0 (pify@3.0.0, semver@5.7.1, parse-author@2.0.0, nodeify@1.0.1, yargs-parser@10.1.0, debug@3.2.6, fs-extra@5.0.0, resolve@1.12.0, extract-zip@1.6.7, plist@2.1.0, galactus@0.2.1, get-package-info@1.0.0, electron-osx-sign@0.4.12, rcedit@1.1.2, asar@0.14.6, electron-download@4.1.1)
> ├── lodash@4.17.15
> └── babel-polyfill@6.26.0 (regenerator-runtime@0.10.5, babel-runtime@6.26.0, core-js@2.6.9)
> 
> C:\Users\vente>nativefier --platform "windows" --icon android-messages-logo.png --name "Google Messages" "https://messages.google.com/web" --honest --disable-dev-tools --single-instance --tray
> C:\Users\vente\AppData\Roaming\npm\node_modules\nativefier\lib\cli.js:89
>     log.info(`App built to ${appPath}`);
>              ^
> SyntaxError: Unexpected token ILLEGAL
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>     at node.js:814:3

I'm running Windows 10 Version 10.0.18362 Build 18362

Any suggestions would be appreciated!
Chuck

**Comment by pbanj** [comment]
you dont need to install anything for this to work on windows. you only ned to do it if you want to rebuild the app and any issues for that wouldnt apply to this it would apply to navfilter
